ver: 5 # config 版本

service: # 訂閱的服務
  - websocket.trem.rts.v1
  - websocket.eq.eew.v1
  - websocket.eq.report.v1

server: # websocket 伺服器地址
  - lb-1.exptech.dev
  - lb-2.exptech.dev
  - lb-3.exptech.dev
  - lb-4.exptech.dev

SHOW_BOTH_EEW: false
WS_OFF_PASS: false