name: Auto PR to infos folder

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Get filename from info.json
        id: get-filename
        run: |
          cd source-repo
          BASE_NAME=$(jq -r '.name' info.json)
          FILENAME="${BASE_NAME}.json"
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          cp info.json ../target.json

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ExpTechTW/TREM-Plugins
          token: ${{ secrets.PAT_TOKEN }}
          path: target-repo

      - name: Copy and commit file
        run: |
          mkdir -p target-repo/infos
          mv target.json "target-repo/infos/${{ steps.get-filename.outputs.filename }}"
          cd target-repo
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b update-file
          git add infos
          git commit -m "Update ${{ steps.get-filename.outputs.filename }}"
          git push origin update-file

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pr_url=$(gh pr create \
            --repo ExpTechTW/TREM-Plugins \
            --base main \
            --head ${{ steps.get-filename.outputs.branch_name }} \
            --title "Update ${{ steps.get-filename.outputs.filename }}" \
            --body "Automated update from plugin repository" \
            --label "auto-merge")
          echo "Created PR: $pr_url"
