name: Auto PR to infos folder

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Get filename from info.json
        id: get-filename
        run: |
          BASE_NAME=$(jq -r '.name' info.json)
          FILENAME="${BASE_NAME}.json"
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Update ${{ steps.get-filename.outputs.filename }}"
          title: "Update ${{ steps.get-filename.outputs.filename }}"
          body: "Automated PR to update JSON file in infos directory"
          branch: "update-${{ steps.get-filename.outputs.filename }}"
          base: main
          delete-branch: true
          path: infos
          repository: ExpTechTW/TREM-Plugins
